global:
  project: default
  baseDomain: ""
  clusterURL: https://kubernetes.default.svc
  
airflow:
  name: airflow
  enabled: true
  syncWave: 0
  namespace: airflow
  dagRepo:
    url: https://github.com/cloud-bulldozer/airflow-kubernetes
    branch: master
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: 1.1.0
  values: 
    executor: KubernetesExecutor
    defaultAirflowRepository: quay.io/cloud-bulldozer/airflow
    defaultAirflowTag: 2.1.3
    airflowVersion: 2.1.3
    config:
      logging:
        colored_console_log: "False"
        remote_logging: "True"
        remote_base_log_folder: s3://perfscale-airflow-logs/ci
        remote_log_conn_id: S3Logs
      kubernetes:
        delete_worker_pods: True
      core:
        DAGBAG_IMPORT_TIMEOUT: 300
        killed_task_cleanup_time: 604800
      scheduler:
        scheduler_heartbeat_sec: 10
        processor_poll_interval: 30
      secrets:
        backend: airflow.providers.hashicorp.secrets.vault.VaultBackend
        backend_kwargs: '{"connections_path": "connections", "variables_path": "variables", "kubernetes_role": "airflow", "auth_type": "kubernetes", "mount_point": "airflow", "url": "http://vault.vault.svc.cluster.local:8200"}'
    dags:
      gitSync:
        enabled: true
        subPath: dags
        depth: 8
    webserver:
      replicas: 3
    migrateDatabaseJob:
      jobAnnotations:
        "argocd.argoproj.io/hook": "Sync"
        "argocd.argoproj.io/hook-delete-policy": "BeforeHookCreation"
        "helm.sh/hook": "pre-install"
        "helm.sh/hook-weight": ""
        "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

argocd: 
  name: argocd
  enabled: true
  syncWave: -10000
  namespace: argocd
  source:
    repoURL: https://github.com/argoproj/argo-helm
    path: argo-helm/charts
    targetRevision: HEAD
  values: {}

dashboard: 
  name: perf-dashboard
  enabled: true
  syncWave: 0
  namespace: perf-dashboard
  source:
    repoURL: https://github.com/whitleykeith/perfscale-stack
    path: charts/components/dashboard
    targetRevision: HEAD
  values: {}

vault:
  name: vault
  enabled: true 
  syncWave: -9999
  namespace: vault
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: ""
  values:
    global:
      openshift: true 