global:
  project: default
  baseDomain: ""
  clusterURL: https://kubernetes.default.svc
  
airflow:
  name: airflow
  enabled: true
  syncWave: 0
  namespace: airflow
  dagRepo:
    url: https://github.com/cloud-bulldozer/airflow-kubernetes
    branch: master
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: 1.1.0
  values: 
    executor: KubernetesExecutor
    defaultAirflowRepository: quay.io/cloud-bulldozer/airflow
    defaultAirflowTag: 2.1.3
    airflowVersion: 2.1.3
    config:
      api:
        auth_backend: airflow.api.auth.backend.basic_auth
      logging:
        colored_console_log: "False"
        remote_logging: "True"
        remote_base_log_folder: s3://perfscale-airflow-logs/ci
        remote_log_conn_id: S3Logs
      kubernetes:
        delete_worker_pods: True
      core:
        DAGBAG_IMPORT_TIMEOUT: 300
        killed_task_cleanup_time: 604800
      scheduler:
        scheduler_heartbeat_sec: 10
        processor_poll_interval: 30
      secrets:
        backend: airflow.providers.hashicorp.secrets.vault.VaultBackend
        backend_kwargs: '{"connections_path": "connections", "variables_path": "variables", "kubernetes_role": "airflow", "auth_type": "kubernetes", "mount_point": "airflow", "url": "http://vault.vault.svc.cluster.local:8200"}'
      webserver:
        instance_name: Performance and Scale
        expose_config: True
        default_ui_timezone: America/New_York
    dags:
      gitSync:
        enabled: true
        subPath: dags
        depth: 8
    webserver:
      replicas: 3
    migrateDatabaseJob:
      jobAnnotations:
        "argocd.argoproj.io/hook": "Sync"
        "argocd.argoproj.io/hook-delete-policy": "BeforeHookCreation"
        "helm.sh/hook": "pre-install"
        "helm.sh/hook-weight": ""
        "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

argocd: 
  name: argocd
  enabled: true
  syncWave: -10000
  namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "x.x.x"
  values:
    fullnameOverride: argocd
    installCRDs: false
    server:
      config:
        repositories: |
          - type: helm
            name: stable
            url: https://charts.helm.sh/stable
          - type: helm
            name: argo-cd
            url: https://argoproj.github.io/argo-helm
          - type: helm
            name: hashicorp
            url: https://helm.releases.hashicorp.com
          - type: helm
            name: grafana
            url: https://grafana.github.io/helm-charts

vault:
  name: vault
  enabled: true 
  syncWave: -9999
  namespace: vault
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "x.x.x"
  values:
    global:
      openshift: true
      enabled: true
    server:
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
    ui:
      enabled: true


dashboard:
  name: dashboard
  enabled: true
  syncWave: 0
  namespace: dashboard
  source:
    repoURL: https://github.com/whitleykeith/perfscale-stack
    path: charts/components/dashboard
    targetRevision: HEAD
  values:
    elasticsearch:
      url: perf-results-es-http.perf-results.svc.cluster.local:9200
      indice: perf_scale_ci
      username: elastic