global:
  project: default
  baseDomain: ""
  clusterURL: https://kubernetes.default.svc

elastic:
  name: perf-results
  enabled: true
  syncWave: 1
  namespace: perf-results
  source:
    repoURL: https://github.com/whitleykeith/perfscale-stack
    path: charts/components/elasticsearch
    targetRevision: HEAD
  values: {}

elasticOperator:
  name: eck-operator
  enabled: true
  syncWave: 0
  namespace: elastic-system
  source:
    repoURL: https://github.com/elastic/cloud-on-k8s
    path: deploy/eck-operator
    targetRevision: HEAD
  values:
    image:
      tag: 1.7.1


thanos:
  name: thanos
  enabled: true
  syncWave: 0
  namespace: thanos
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: thanos
    targetRevision: "x.x.x"
  values: {}

loki:
  name: loki
  enabled: true
  syncWave: 0
  namespace: loki
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "x.x.x"
  values:
    persistence:
      enabled: true
      size: 1024Gi

promtail: 
  name: promtail
  enabled: true
  syncWave: 0
  namespace: promtail
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: "x.x.x"
  values: 
    securityContext: 
      privileged: true
      allowPrivilegeEscalation: true
    containerSecurityContext:
      privileged: true
      allowPrivilegeEscalation: true
    config:
      lokiAddress: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
  

grafana: 
  name: grafana
  enabled: true
  syncWave: 0
  namespace: grafana
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "x.x.x"
  values:
    persistence:
      enabled: true
      size: 1024Gi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Cluster Prometheus
          type: prometheus
          access: proxy
          url: https://prometheus-k8s.openshift-monitoring.svc:9091
        - name: Thanos
          type: prometheus
          access: proxy
          url: http://thanos-query.thanos.svc.cluster.local:9090
        - name: Loki 
          type: loki
          access: proxy
          url: http://loki.loki.svc.cluster.local:3100