global:
  project: default
  baseDomain: ""
  clusterURL: https://kubernetes.default.svc

elastic:
  name: perf-results
  enabled: true
  syncWave: 1
  namespace: perf-results
  source:
    repoURL: https://github.com/whitleykeith/perfscale-stack
    path: charts/components/elasticsearch
    targetRevision: HEAD
  values: {}

elasticOperator:
  name: eck-operator
  enabled: true
  syncWave: 0
  namespace: elastic-system
  source:
    repoURL: https://github.com/elastic/cloud-on-k8s
    path: deploy/eck-operator
    targetRevision: HEAD
  values:
    image:
      tag: 1.7.1


thanos:
  name: thanos
  enabled: true
  syncWave: 0
  namespace: thanos
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: thanos
    targetRevision: "x.x.x"
  values:
    image:
      repository: thanosio/thanos
      tag: v0.22.0
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: openshift-monitoring
    existingObjstoreSecret: thanos-objstore-secret
    query:
      logLevel: debug
      replicaLabel:
        - prometheus_replica
        - replica
    receive:
      enabled: true
      logLevel: debug
      mode: dual-mode
      distributor:
        replicaCount: 3
      nodeSelector:
        node.kubernetes.io/instance-type: r5.16xlarge
      tsdbRetention: 14d
      resources:
        requests:
          cpu: 3
          memory: 450Gi
        limits:
          memory: 450Gi
      service:
        additionalHeadless: true
        remoteWrite:
          port: 19291
      replicaCount: 4
      persistence:
        enabled: true
        size: 1024Gi
    storegateway:
      logLevel: debug 
      extraFlags:
      - "--max-time=-14d"
      resources:
        requests:
          cpu: 3
          memory: 10Gi
        limits:
          memory: 200Gi
      nodeSelector:
        node.kubernetes.io/instance-type: r5.16xlarge
      enabled: true
      replicaCount: 1
      persistence:
        size: 1024Gi
      service:
        additionalHeadless: true
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      persistence:
        size: 1024Gi
      retentionResolutionRaw: 14d
      retentionResolution5m: 30d
      retentionResolution1h: 60d

    ruler:
      enabled: true
      alertmanagers:
        - alertmanager-main.openshift-monitoring.svc.cluster.local:9094
      config:
        groups:
          - name: cluster_status
            rules:
            - alert: ClusterAPIServerUp
              expr: sum(up{apiserver="openshift-apiserver"}) by (openshift_cluster_name) == 3
              for: 5m
              labels:
                severity: info
              annotations:
                summary: Cluster {{ "{{$labels.openshift_cluster_name}}" }} API Servers are up

            

loki:
  name: loki
  enabled: true
  syncWave: 0
  namespace: loki
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "x.x.x"
  values:
    persistence:
      enabled: true
      size: 1024Gi

promtail: 
  name: promtail
  enabled: true
  syncWave: 0
  namespace: promtail
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: "x.x.x"
  values: 
    securityContext: 
      privileged: true
      allowPrivilegeEscalation: true
    containerSecurityContext:
      privileged: true
      allowPrivilegeEscalation: true
    config:
      lokiAddress: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
  

grafana: 
  name: grafana
  enabled: true
  syncWave: 0
  namespace: grafana
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "x.x.x"
  values:
    persistence:
      enabled: true
      size: 1024Gi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Cluster Prometheus
          type: prometheus
          access: proxy
          url: https://prometheus-k8s.openshift-monitoring.svc:9091
        - name: Thanos
          type: prometheus
          access: proxy
          url: http://thanos-query.thanos.svc.cluster.local:9090
        - name: Loki 
          type: loki
          access: proxy
          url: http://loki.loki.svc.cluster.local:3100