{{ if .Values.airflow.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.airflow.syncWave | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  destination: 
    namespace: {{ .Values.airflow.namespace }}
    server: {{ .Values.global.clusterURL }}
  source:
    repoURL: {{ .Values.airflow.source.repoURL }}
    chart: {{ .Values.airflow.source.chart }} 
    targetRevision: {{ .Values.airflow.source.targetRevision | default "HEAD" }}
    helm:
      releaseName: {{ .Values.airflow.name }}
{{- with .Values.airflow.values }}
      values: |-
{{- toYaml . | nindent 8 }}
        env:
        - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH
          value: repo/
        - name: AIRFLOW__CORE__KILLED_TASK_CLEANUP_TIME
          value: 604800
        - name: GIT_REPO
          value: {{ $.Values.airflow.dagRepo.url }}
        - name: GIT_BRANCH
          value: {{ $.Values.airflow.dagRepo.branch }}
{{- end }}        
      parameters:
      - name: dags.gitSync.repo
        value: {{ .Values.airflow.dagRepo.url }}
      - name: dags.gitSync.branch
        value: {{ .Values.airflow.dagRepo.branch }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.airflow.name }}
  namespace: {{ .Values.airflow.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.airflow.syncWave | quote }}
spec:
  host: {{ .Values.airflow.name }}.{{ .Values.global.baseDomain }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Values.airflow.name }}-webserver
    weight: 100
  wildcardPolicy: None
{{ end }}