{{ if .Values.argocd.enabled }} 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argocd.syncWave | default "0" | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  destination: 
    namespace: {{ .Values.argocd.namespace }}
    server: {{ .Values.global.clusterURL }}
  source:
    repoURL: {{ .Values.argocd.source.repoURL }}
    chart: {{ .Values.argocd.source.chart }} 
    targetRevision: {{ .Values.argocd.source.targetRevision | default "x.x.x" }}
    helm:
      releaseName: {{ .Values.argocd.name }}
{{- with .Values.argocd.values }}
      values: |-
{{- toYaml . | nindent 8 }}
{{- end }}
      parameters:
      - name: server.route.enabled
        value: "true"
      - name: server.route.hostname
        value: {{ .Values.argocd.name }}.{{ .Values.global.baseDomain }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{ end }}