apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perfscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination: 
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/whitleykeith/perfscale-stack
    path: charts/stacks/perfscale
    targetRevision: HEAD
    helm:
      releaseName: perfscale
      values: |-
        global:
          baseDomain: $_cluster_domain
        airflow:
          values:
            config:
              webserver:
                base_url: http://airflow.$_cluster_domain
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true










