apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}

spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: {{ .Values.version }}
{{- with .Values.elasticsearch.nodeSets }}
  nodeSets:
  {{- toYaml . | nindent 2 }}
{{- end }}